// Package recovery implements one-time recovery codes as a fallback for
// two-factor authentication: when a user loses their TOTP device or
// passkey, a recovery code lets them regain access without a support-driven
// bypass.
//
// Codes are generated from crypto/rand, displayed to the user exactly once,
// and only their SHA-256 hashes are persisted via the Store interface that
// the consumer implements.
package recovery

import (
	"context"
	"crypto/rand"
	"crypto/sha256"
	"encoding/base32"
	"encoding/hex"
	"errors"
	"strings"
)

// ErrCodeInvalid is returned when a supplied recovery code does not match
// any stored, unused code for the user.
var ErrCodeInvalid = errors.New("recovery: invalid code")

// defaultCount is the number of recovery codes generated when WithCount is
// not supplied.
const defaultCount = 10

// codeBytes is the number of crypto/rand bytes per code. 10 bytes base32
// no-padding-encodes to exactly 16 characters.
const codeBytes = 10

// Config holds recovery code generation parameters.
type Config struct {
	Count int
}

// Option is a functional option for configuring the recovery Service.
type Option func(*Config)

// WithCount sets the number of recovery codes generated by Generate.
// Values less than 1 are ignored and the default (10) is kept.
func WithCount(n int) Option {
	return func(c *Config) {
		if n >= 1 {
			c.Count = n
		}
	}
}

// Service manages recovery code generation and consumption.
type Service struct {
	store Store
	cfg   Config
}

// NewService creates a new recovery code Service backed by store.
func NewService(store Store, opts ...Option) *Service {
	cfg := Config{Count: defaultCount}
	for _, opt := range opts {
		opt(&cfg)
	}
	return &Service{store: store, cfg: cfg}
}

// Generate creates a fresh set of recovery codes for userID, atomically
// replacing any previously issued set. It returns the plaintext codes for
// one-time display to the user; only their hashes are persisted, so the
// plaintext values cannot be recovered later.
func (s *Service) Generate(ctx context.Context, userID string) ([]string, error) {
	codes := make([]string, s.cfg.Count)
	hashes := make([]string, s.cfg.Count)
	for i := range codes {
		code, err := generateCode()
		if err != nil {
			return nil, err
		}
		codes[i] = code
		hashes[i] = hashCode(code)
	}

	if err := s.store.ReplaceCodes(ctx, userID, hashes); err != nil {
		return nil, err
	}
	return codes, nil
}

// Consume validates and consumes a single-use recovery code for userID.
// Input is normalized before comparison, so case, surrounding whitespace,
// and dash grouping don't matter. A code can only be consumed once.
func (s *Service) Consume(ctx context.Context, userID, code string) error {
	err := s.store.ConsumeCode(ctx, userID, hashCode(code))
	if errors.Is(err, ErrCodeNotFound) {
		return ErrCodeInvalid
	}
	return err
}

// Remaining reports the number of unused recovery codes for userID.
func (s *Service) Remaining(ctx context.Context, userID string) (int, error) {
	return s.store.CountCodes(ctx, userID)
}

// Disable removes all recovery codes for userID.
func (s *Service) Disable(ctx context.Context, userID string) error {
	return s.store.DeleteCodes(ctx, userID)
}

// generateCode produces a fresh recovery code from crypto/rand, formatted
// for display as lowercase "xxxx-xxxx-xxxx-xxxx".
func generateCode() (string, error) {
	b := make([]byte, codeBytes)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	encoded := base32.StdEncoding.WithPadding(base32.NoPadding).EncodeToString(b)
	return formatCode(strings.ToLower(encoded)), nil
}

// formatCode groups a flat code into hyphenated 4-character blocks.
func formatCode(s string) string {
	var groups []string
	for i := 0; i < len(s); i += 4 {
		end := min(i+4, len(s))
		groups = append(groups, s[i:end])
	}
	return strings.Join(groups, "-")
}

// canonical normalizes a user-supplied code for hashing: it trims
// surrounding whitespace, strips dashes and internal spaces, and
// uppercases the result.
func canonical(code string) string {
	code = strings.ToUpper(strings.ReplaceAll(strings.TrimSpace(code), "-", ""))
	return strings.ReplaceAll(code, " ", "")
}

// hashCode returns the SHA-256 hex digest of the canonical form of code.
func hashCode(code string) string {
	h := sha256.Sum256([]byte(canonical(code)))
	return hex.EncodeToString(h[:])
}
